name: sugar_catch
description: "Track hidden sugar in grocery foods with barcode scanning."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.3+1
  hive_ce: ^2.13.2
  hive_ce_flutter: ^2.3.2
  hooks_riverpod: ^2.6.1
  mobile_scanner: ^7.0.1
  http: ^1.5.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^16.2.2
  heroicons: ^0.11.0
  fl_chart: ^1.1.1
  in_app_review: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  hive_ce_generator: ^1.9.2
  build_runner: ^2.4.13
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/