name: sweetr
description: "Track hidden sugar in grocery foods with barcode scanning."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.3+1
  hive_ce: ^2.13.2
  hive_ce_flutter: ^2.3.2
  hooks_riverpod: ^2.6.1
  mobile_scanner: ^7.0.1
  http: ^1.5.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^16.2.2
  heroicons: ^0.11.0
  fl_chart: ^1.1.1
  in_app_review: ^2.0.11
  mixpanel_flutter: ^2.4.4
  envied: ^1.3.0
  purchases_flutter: ^9.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  hive_ce_generator: ^1.9.2
  build_runner: ^2.4.13
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3
  envied_generator: ^1.1.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#ffffff"
    theme_color: "#00ff00"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"